apiVersion: v1
kind: ConfigMap
metadata:
  name: coinbreakr-config
  labels:
    app: coinbreakr-api
    environment: testing
data:
  jwt-expires-in: "2d"
  rate-limit-window-ms: "900000"
  rate-limit-max-requests: "100"
